// Generated by CoffeeScript 1.6.3
(function() {
  var app, should;

  app = require(process.cwd() + "/src/app");

  should = require('chai').should;

  should();

  describe('AiR Service API for operator', function() {
    it('should have "/" for index.html', function() {
      var expectedMethod, routines;
      expectedMethod = "/";
      routines = app.routes.get.filter(function(item) {
        return item.path === expectedMethod;
      });
      return routines.length.should.equal(1);
    });
    it('should have "/search"', function() {
      var expectedMethod, qualifiedRoutines;
      expectedMethod = '/search';
      qualifiedRoutines = app.routes.get.filter(function(item) {
        return item.path === expectedMethod;
      });
      return qualifiedRoutines.length.should.equal(1);
    });
    it('should have "/testCard/:testCardId"', function() {
      var expectedMethod, qualifiedRoutines;
      expectedMethod = '/testCard/:testCardId';
      qualifiedRoutines = app.routes.get.filter(function(item) {
        return item.path === expectedMethod;
      });
      return qualifiedRoutines.length.should.equal(1);
    });
    return it('should have /result/:orderNumber/:sessionKey', function() {
      var expectedMethod, qualifiedRoutines;
      expectedMethod = '/result/:orderNumber/:sessionKey';
      qualifiedRoutines = app.routes.get.filter(function(item) {
        return item.path === expectedMethod;
      });
      return qualifiedRoutines.length.should.equal(1);
    });
  });

}).call(this);
