// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = require(process.cwd() + '/src/app');

  describe('AiR Service for developer', function() {
    it('should have /develop', function() {
      var expectedMethod, routines;
      expectedMethod = '/develop';
      routines = app.routes.get.filter(function(item) {
        return item.path === expectedMethod;
      });
      return routines.length.should.equal(1);
    });
    return it('should have /develop/newTestCardId', function() {
      var expectedMethod, routines;
      expectedMethod = '/develop/newTestCardId';
      routines = app.routes.get.filter(function(item) {
        return item.path === expectedMethod;
      });
      return routines.length.should.equal(1);
    });
  });

}).call(this);
