// Generated by CoffeeScript 1.6.3
(function() {
  var app, request;

  app = require(process.cwd() + "/src/app");

  request = require('supertest');

  describe('AiR Service for operator', function() {
    return it('pure testing', function(done) {
      var airService;
      airService = request(app);
      return airService.get('/search?model=3458A').end(function(err, res) {
        res.body.model.should.equal('3458A');
        return done();
      });
    });
  });

}).call(this);
