// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = require(process.cwd() + "/src/app");

  describe('AiR Services API for Admin', function() {
    it('should have /admin page', function() {
      var expectedMethod, routines;
      expectedMethod = '/admin';
      routines = app.routes.get.filter(function(item) {
        return item.path === expectedMethod;
      });
      return routines.length.should.equal(1);
    });
    it('should have "/admin/release"', function() {
      var expectedMethod, routines;
      expectedMethod = '/admin/release';
      routines = app.routes.get.filter(function(item) {
        return item.path === expectedMethod;
      });
      return routines.length.should.equal(1);
    });
    return it('should have "/admin/approve"', function() {
      var expectedMethod, routines;
      expectedMethod = '/admin/approve';
      routines = app.routes.get.filter(function(item) {
        return item.path === expectedMethod;
      });
      return routines.length.should.equal(1);
    });
  });

}).call(this);
