// Generated by CoffeeScript 1.6.3
var app, chai, nock, request, services;

request = require('supertest');

chai = require('chai');

app = require(process.cwd() + '\\src\\app');

services = require(process.cwd() + '\\src\\services');

nock = require('nock');

chai.should();

describe('testing function', function() {
  it('should return 200 status', function(done) {
    var airService;
    airService = request('http://localhost:9898');
    return airService.get('/search?order=1-12345-1').end(function(err, res) {
      res.body.order.should.equal('1-12345-1');
      res.status.should.equal(200);
      return done();
    });
  });
  return it('should use supertest to simulating hosting server', function(done) {
    var localAirServer;
    localAirServer = request(app);
    return localAirServer.get('/search?order=1-12345-1').end(function(err, res) {
      var servicesMock;
      servicesMock = nock(services.addressLink).get('/search?order=1-12345-1').reply(200, {
        order: '1-12345-1'
      });
      res.body.order.should.equal('1-12345-1');
      res.status.should.equal(200);
      return done();
    });
  });
});
