// Generated by CoffeeScript 1.6.3
(function() {
  var app, chai, nock, request, services;

  request = require('supertest');

  chai = require('chai');

  app = require(process.cwd() + '\\src\\app');

  services = require(process.cwd() + '\\src\\services');

  nock = require('nock');

  chai.should();

  describe('testing function', function() {});

}).call(this);
