// Generated by CoffeeScript 1.6.3
(function() {
  var app, nock, request, should;

  request = require('supertest');

  app = require(process.cwd() + '/src/app');

  nock = require('nock');

  should = require('chai').should;

  should();

  describe('AiR RESTFul APIs', function() {});

}).call(this);
