// Generated by CoffeeScript 1.6.3
var app, request, scope, should;

request = require('supertest');

app = process.cwd() + '/src/app.coffee';

scope = require('nock');

should = require('chai').should;

should();

describe('AiR RESTFul APIs', function() {
  return it('should return fake cso if searching "order"', function(done) {
    scope = scope('C:\\SOURCE\\AiRServer\\src\\app.js').get('/search?order=1-12345-1').reply({
      order: "1-12345-1"
    });
    return request(app).get('/search?order=1-12345-1').end(function(err, res) {
      res.should.have.status(500);
      scope.done();
      return done();
    });
  });
});
