// Generated by CoffeeScript 1.6.3
var app, nock, request, should;

request = require('supertest');

app = require(process.cwd() + '/src/app');

nock = require('nock');

should = require('chai').should;

should();

describe('AiR RESTFul APIs', function() {
  return it('should return fake cso if searching "order"', function(done) {
    var scope;
    scope = nock("http://localhost:" + (app.get('port'))).get('/search?order=1-12345-1').reply(200, {
      order: "1-12345-1"
    });
    return request('http://localhost:9898').get('/search?order=1-12345-1').end(function(err, res) {
      res.status.should.equal(200);
      res.body.order.should.equal('1-12345-1');
      scope.done();
      return done();
    });
  });
});
