// Generated by CoffeeScript 1.6.3
var app, config, express, route;

express = require('express');

config = require('./config');

route = require('./route');

app = express();

config(app);

route(app);

module.exports = app;
