// Generated by CoffeeScript 1.6.3
var config, express;

express = require('express');

config = function(app) {
  app.set('port', process.env.PORT || 9898);
  app.use(express.logger());
  app.use(express.compress());
  app.use(express.methodOverride());
  app.use(express.bodyParser());
  return app.use(function(err, req, res, next) {
    console.error(error.stack);
    return res.send(500, 'something broke!');
  });
};

module.exports = config;
