// Generated by CoffeeScript 1.6.3
var searchModel;

searchModel = function(modelNumber, callback) {
  var result;
  result = {
    model: modelNumber
  };
  return callback(result);
};

module.exports = searchModel;
