// Generated by CoffeeScript 1.6.3
var searchResult;

searchResult = function(orderNumber, callback) {
  var result;
  result = {
    order: orderNumber
  };
  return callback(result);
};

module.exports = searchResult;
