// Generated by CoffeeScript 1.6.3
var search, searchModel, searchResult;

searchModel = require('./searchModel');

searchResult = require('./searchResult');

search = function(req, callback) {
  if (req.param('model')) {
    searchModel(req.param('model'), function(result) {
      return callback(result);
    });
  }
  if (req.param('order')) {
    searchResult(req.param('order'), function(result) {
      return callback(result);
    });
  }
  if (req.param('orderNumber')) {
    return searchResult(req.param('order'), function(result) {
      return callback(result);
    });
  }
};

module.exports = search;
